-- MySQL Script generated by MySQL Workbench
-- Sun Apr 14 23:14:01 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Game`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Game` (
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Director`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Director` (
  `Name` VARCHAR(45) NOT NULL,
  `Age` INT NOT NULL,
  `SkillPoints` INT NOT NULL,
  `Game_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Name`, `Game_Name`),
  INDEX `fk_Director_Game1_idx` (`Game_Name` ASC) VISIBLE,
  CONSTRAINT `fk_Director_Game1`
    FOREIGN KEY (`Game_Name`)
    REFERENCES `mydb`.`Game` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Director_idolises_Director`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Director_idolises_Director` (
  `Director_Name` VARCHAR(45) NOT NULL,
  `Director_Game_Name` VARCHAR(45) NOT NULL,
  `Director_Name1` VARCHAR(45) NOT NULL,
  `Director_Game_Name1` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Director_Name`, `Director_Game_Name`, `Director_Name1`, `Director_Game_Name1`),
  INDEX `fk_Director_has_Director_Director2_idx` (`Director_Name1` ASC, `Director_Game_Name1` ASC) VISIBLE,
  INDEX `fk_Director_has_Director_Director1_idx` (`Director_Name` ASC, `Director_Game_Name` ASC) VISIBLE,
  CONSTRAINT `fk_Director_has_Director_Director1`
    FOREIGN KEY (`Director_Name` , `Director_Game_Name`)
    REFERENCES `mydb`.`Director` (`Name` , `Game_Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Director_has_Director_Director2`
    FOREIGN KEY (`Director_Name1` , `Director_Game_Name1`)
    REFERENCES `mydb`.`Director` (`Name` , `Game_Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Country` (
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Director_is_from_Country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Director_is_from_Country` (
  `Director_Name` VARCHAR(45) NOT NULL,
  `Director_Game_Name` VARCHAR(45) NOT NULL,
  `Country_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Director_Name`, `Director_Game_Name`, `Country_Name`),
  INDEX `fk_Director_has_Country_Country1_idx` (`Country_Name` ASC) VISIBLE,
  INDEX `fk_Director_has_Country_Director1_idx` (`Director_Name` ASC, `Director_Game_Name` ASC) VISIBLE,
  CONSTRAINT `fk_Director_has_Country_Director1`
    FOREIGN KEY (`Director_Name` , `Director_Game_Name`)
    REFERENCES `mydb`.`Director` (`Name` , `Game_Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Director_has_Country_Country1`
    FOREIGN KEY (`Country_Name`)
    REFERENCES `mydb`.`Country` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`City`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`City` (
  `Name` VARCHAR(45) NOT NULL,
  `Country_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Name`, `Country_Name`),
  INDEX `fk_City_Country1_idx` (`Country_Name` ASC) VISIBLE,
  CONSTRAINT `fk_City_Country1`
    FOREIGN KEY (`Country_Name`)
    REFERENCES `mydb`.`Country` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Actor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Actor` (
  `Name` VARCHAR(45) NOT NULL,
  `Photo` BLOB NOT NULL,
  `Birthdate` DATE NOT NULL,
  PRIMARY KEY (`Name`, `Photo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Actor_is_from_Country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Actor_is_from_Country` (
  `Actor_Name` VARCHAR(45) NOT NULL,
  `Actor_Photo` BLOB NOT NULL,
  `Country_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Actor_Name`, `Actor_Photo`, `Country_Name`),
  INDEX `fk_Actor_has_Country_Country2_idx` (`Country_Name` ASC) VISIBLE,
  INDEX `fk_Actor_has_Country_Actor2_idx` (`Actor_Name` ASC, `Actor_Photo` ASC) VISIBLE,
  CONSTRAINT `fk_Actor_has_Country_Actor2`
    FOREIGN KEY (`Actor_Name` , `Actor_Photo`)
    REFERENCES `mydb`.`Actor` (`Name` , `Photo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Actor_has_Country_Country2`
    FOREIGN KEY (`Country_Name`)
    REFERENCES `mydb`.`Country` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Company` (
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Genre` (
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Script`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Script` (
  `Title` VARCHAR(45) NOT NULL,
  `Genre_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Title`, `Genre_Name`),
  INDEX `fk_Script_Genre1_idx` (`Genre_Name` ASC) VISIBLE,
  CONSTRAINT `fk_Script_Genre1`
    FOREIGN KEY (`Genre_Name`)
    REFERENCES `mydb`.`Genre` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.```
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.``` (
  `Title` VARCHAR(45) NOT NULL,
  `ReleaseYear` YEAR(4) NOT NULL,
  `Company_Name` VARCHAR(45) NOT NULL,
  `Script_Title` VARCHAR(45) NOT NULL,
  `Script_Genre_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Title`, `ReleaseYear`, `Company_Name`),
  INDEX `fk_Movie_Company1_idx` (`Company_Name` ASC) VISIBLE,
  INDEX `fk_Movie_Script1_idx` (`Script_Title` ASC, `Script_Genre_Name` ASC) VISIBLE,
  CONSTRAINT `fk_Movie_Company1`
    FOREIGN KEY (`Company_Name`)
    REFERENCES `mydb`.`Company` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Movie_Script1`
    FOREIGN KEY (`Script_Title` , `Script_Genre_Name`)
    REFERENCES `mydb`.`Script` (`Title` , `Genre_Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Role` (
  `CharacterName` VARCHAR(45) NOT NULL,
  `Actor_Name` VARCHAR(45) NOT NULL,
  `Movie_Title` VARCHAR(45) NOT NULL,
  `Movie_ReleaseYear` YEAR(4) NOT NULL,
  `Movie_Company_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CharacterName`, `Actor_Name`, `Movie_Title`, `Movie_ReleaseYear`, `Movie_Company_Name`),
  INDEX `fk_Role_Actor1_idx` (`Actor_Name` ASC) VISIBLE,
  INDEX `fk_Role_Movie1_idx` (`Movie_Title` ASC, `Movie_ReleaseYear` ASC, `Movie_Company_Name` ASC) VISIBLE,
  CONSTRAINT `fk_Role_Actor1`
    FOREIGN KEY (`Actor_Name`)
    REFERENCES `mydb`.`Actor` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Role_Movie1`
    FOREIGN KEY (`Movie_Title` , `Movie_ReleaseYear` , `Movie_Company_Name`)
    REFERENCES `mydb`.``` (`Title` , `ReleaseYear` , `Company_Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sponsor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sponsor` (
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Movie_has_Sponsor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Movie_has_Sponsor` (
  `Movie_Title` VARCHAR(45) NOT NULL,
  `Movie_ReleaseYear` YEAR(4) NOT NULL,
  `Movie_Company_Name` VARCHAR(45) NOT NULL,
  `Sponsor_Name` VARCHAR(45) NOT NULL,
  `MoneyOffered` INT NOT NULL,
  PRIMARY KEY (`Movie_Title`, `Movie_ReleaseYear`, `Movie_Company_Name`, `Sponsor_Name`),
  INDEX `fk_Movie_has_Sponsor_Sponsor1_idx` (`Sponsor_Name` ASC) VISIBLE,
  INDEX `fk_Movie_has_Sponsor_Movie1_idx` (`Movie_Title` ASC, `Movie_ReleaseYear` ASC, `Movie_Company_Name` ASC) VISIBLE,
  CONSTRAINT `fk_Movie_has_Sponsor_Movie1`
    FOREIGN KEY (`Movie_Title` , `Movie_ReleaseYear` , `Movie_Company_Name`)
    REFERENCES `mydb`.``` (`Title` , `ReleaseYear` , `Company_Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Movie_has_Sponsor_Sponsor1`
    FOREIGN KEY (`Sponsor_Name`)
    REFERENCES `mydb`.`Sponsor` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Set`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Set` (
  `SetID` INT NOT NULL,
  `City_Name` VARCHAR(45) NOT NULL,
  `City_Country_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`SetID`, `City_Name`, `City_Country_Name`),
  INDEX `fk_Set_City1_idx` (`City_Name` ASC, `City_Country_Name` ASC) VISIBLE,
  CONSTRAINT `fk_Set_City1`
    FOREIGN KEY (`City_Name` , `City_Country_Name`)
    REFERENCES `mydb`.`City` (`Name` , `Country_Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Text`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Text` (
  `Text` LONGTEXT NOT NULL,
  `Previous_text` LONGTEXT NULL,
  `Duration` INT NOT NULL,
  PRIMARY KEY (`Text`),
  INDEX `fk_Text_Text1_idx` (`Previous_text` ASC) VISIBLE,
  CONSTRAINT `fk_Text_Text1`
    FOREIGN KEY (`Previous_text`)
    REFERENCES `mydb`.`Text` (`Text`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Text_is_in_Script`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Text_is_in_Script` (
  `Text_Text` LONGTEXT NOT NULL,
  `Script_Title` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Text_Text`, `Script_Title`),
  INDEX `fk_Text_has_Script_Script1_idx` (`Script_Title` ASC) VISIBLE,
  INDEX `fk_Text_has_Script_Text1_idx` (`Text_Text` ASC) VISIBLE,
  CONSTRAINT `fk_Text_has_Script_Text1`
    FOREIGN KEY (`Text_Text`)
    REFERENCES `mydb`.`Text` (`Text`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Text_has_Script_Script1`
    FOREIGN KEY (`Script_Title`)
    REFERENCES `mydb`.`Script` (`Title`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RoleType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RoleType` (
  `Type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Actor_can_play_RoleType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Actor_can_play_RoleType` (
  `RoleType_Type` VARCHAR(45) NOT NULL,
  `Actor_Name` VARCHAR(45) NOT NULL,
  `Actor_Photo` BLOB NOT NULL,
  PRIMARY KEY (`RoleType_Type`, `Actor_Name`, `Actor_Photo`),
  INDEX `fk_RoleType_has_Actor_Actor1_idx` (`Actor_Name` ASC, `Actor_Photo` ASC) VISIBLE,
  INDEX `fk_RoleType_has_Actor_RoleType1_idx` (`RoleType_Type` ASC) VISIBLE,
  CONSTRAINT `fk_RoleType_has_Actor_RoleType1`
    FOREIGN KEY (`RoleType_Type`)
    REFERENCES `mydb`.`RoleType` (`Type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RoleType_has_Actor_Actor1`
    FOREIGN KEY (`Actor_Name` , `Actor_Photo`)
    REFERENCES `mydb`.`Actor` (`Name` , `Photo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Actor_plays_in_Movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Actor_plays_in_Movie` (
  `Actor_Name` VARCHAR(45) NOT NULL,
  `Actor_Photo` BLOB NOT NULL,
  `Movie_Title` VARCHAR(45) NOT NULL,
  `Movie_ReleaseYear` YEAR(4) NOT NULL,
  `Movie_Company_Name` VARCHAR(45) NOT NULL,
  `StartDate` DATE NOT NULL,
  `EndDate` DATE NOT NULL,
  `YearlyPay` INT NOT NULL,
  PRIMARY KEY (`Actor_Name`, `Actor_Photo`, `Movie_Title`, `Movie_ReleaseYear`, `Movie_Company_Name`),
  INDEX `fk_Actor_has_Movie_Movie1_idx` (`Movie_Title` ASC, `Movie_ReleaseYear` ASC, `Movie_Company_Name` ASC) VISIBLE,
  INDEX `fk_Actor_has_Movie_Actor1_idx` (`Actor_Name` ASC, `Actor_Photo` ASC) VISIBLE,
  CONSTRAINT `fk_Actor_has_Movie_Actor1`
    FOREIGN KEY (`Actor_Name` , `Actor_Photo`)
    REFERENCES `mydb`.`Actor` (`Name` , `Photo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Actor_has_Movie_Movie1`
    FOREIGN KEY (`Movie_Title` , `Movie_ReleaseYear` , `Movie_Company_Name`)
    REFERENCES `mydb`.``` (`Title` , `ReleaseYear` , `Company_Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TrainingProgram`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TrainingProgram` (
  `ProgramID` INT NOT NULL,
  `Cooldown` INT NOT NULL,
  `ExtraAthleticism` INT NULL,
  `ExtraFantasy` INT NULL,
  `ExtraEmotionalFluency` INT NULL,
  `ExtraBodyLanguage` INT NULL,
  `ExtraSpeechClarity` INT NULL,
  `ExtraVoice` INT NULL,
  `ExtraImprovisation` INT NULL,
  `ExtraAttentionToDetail` INT NULL,
  `ExtraMimicking` INT NULL,
  PRIMARY KEY (`ProgramID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Actor_can_do_TrainingProgram`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Actor_can_do_TrainingProgram` (
  `TrainingProgram_ProgramID` INT NOT NULL,
  `Actor_Name` VARCHAR(45) NOT NULL,
  `Actor_Photo` BLOB NOT NULL,
  PRIMARY KEY (`TrainingProgram_ProgramID`, `Actor_Name`, `Actor_Photo`),
  INDEX `fk_TrainingProgram_has_Actor_Actor1_idx` (`Actor_Name` ASC, `Actor_Photo` ASC) VISIBLE,
  INDEX `fk_TrainingProgram_has_Actor_TrainingProgram1_idx` (`TrainingProgram_ProgramID` ASC) VISIBLE,
  CONSTRAINT `fk_TrainingProgram_has_Actor_TrainingProgram1`
    FOREIGN KEY (`TrainingProgram_ProgramID`)
    REFERENCES `mydb`.`TrainingProgram` (`ProgramID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TrainingProgram_has_Actor_Actor1`
    FOREIGN KEY (`Actor_Name` , `Actor_Photo`)
    REFERENCES `mydb`.`Actor` (`Name` , `Photo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PhysicalStats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PhysicalStats` (
  `Actor_Name` VARCHAR(45) NOT NULL,
  `Actor_Photo` BLOB NOT NULL,
  `Height` INT NOT NULL,
  `Weight` INT NOT NULL,
  `Looks` INT NOT NULL,
  `Athleticism` INT NOT NULL,
  PRIMARY KEY (`Actor_Name`, `Actor_Photo`),
  CONSTRAINT `fk_PhysicalStats_Actor1`
    FOREIGN KEY (`Actor_Name` , `Actor_Photo`)
    REFERENCES `mydb`.`Actor` (`Name` , `Photo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`IntelligenceStats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`IntelligenceStats` (
  `Actor_Name` VARCHAR(45) NOT NULL,
  `Actor_Photo` BLOB NOT NULL,
  `Fantasy` INT NOT NULL,
  `EmotionalFluency` INT NOT NULL,
  `BodyLanguage` INT NOT NULL,
  `SpeechClarity` INT NOT NULL,
  PRIMARY KEY (`Actor_Name`, `Actor_Photo`),
  CONSTRAINT `fk_IntelligenceStats_Actor1`
    FOREIGN KEY (`Actor_Name` , `Actor_Photo`)
    REFERENCES `mydb`.`Actor` (`Name` , `Photo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TechnicalStats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TechnicalStats` (
  `Actor_Name` VARCHAR(45) NOT NULL,
  `Actor_Photo` BLOB NOT NULL,
  `Voice` INT NOT NULL,
  `Improvisation` INT NOT NULL,
  `AttentionToDetail` INT NOT NULL,
  `Mimicking` INT NOT NULL,
  PRIMARY KEY (`Actor_Name`, `Actor_Photo`),
  CONSTRAINT `fk_TechnicalStats_Actor1`
    FOREIGN KEY (`Actor_Name` , `Actor_Photo`)
    REFERENCES `mydb`.`Actor` (`Name` , `Photo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Competition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Competition` (
  `Name` VARCHAR(45) NOT NULL,
  `Date` DATE NULL,
  PRIMARY KEY (`Name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Competition_in_Country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Competition_in_Country` (
  `Competition_Name` VARCHAR(45) NOT NULL,
  `Country_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Competition_Name`, `Country_Name`),
  INDEX `fk_Competition_has_Country_Country1_idx` (`Country_Name` ASC) VISIBLE,
  INDEX `fk_Competition_has_Country_Competition1_idx` (`Competition_Name` ASC) VISIBLE,
  CONSTRAINT `fk_Competition_has_Country_Competition1`
    FOREIGN KEY (`Competition_Name`)
    REFERENCES `mydb`.`Competition` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Competition_has_Country_Country1`
    FOREIGN KEY (`Country_Name`)
    REFERENCES `mydb`.`Country` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Award`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Award` (
  `Name` VARCHAR(45) NOT NULL,
  `Points` INT NOT NULL,
  PRIMARY KEY (`Name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Award_is_given_in_Competition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Award_is_given_in_Competition` (
  `Award_Name` VARCHAR(45) NOT NULL,
  `Competition_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Award_Name`, `Competition_Name`),
  INDEX `fk_Award_has_Competition_Competition1_idx` (`Competition_Name` ASC) VISIBLE,
  INDEX `fk_Award_has_Competition_Award1_idx` (`Award_Name` ASC) VISIBLE,
  CONSTRAINT `fk_Award_has_Competition_Award1`
    FOREIGN KEY (`Award_Name`)
    REFERENCES `mydb`.`Award` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Award_has_Competition_Competition1`
    FOREIGN KEY (`Competition_Name`)
    REFERENCES `mydb`.`Competition` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Movie_takes_part_in_Competition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Movie_takes_part_in_Competition` (
  `Movie_Title` VARCHAR(45) NOT NULL,
  `Movie_ReleaseYear` YEAR(4) NOT NULL,
  `Movie_Company_Name` VARCHAR(45) NOT NULL,
  `Competition_Name` VARCHAR(45) NOT NULL,
  `Nominations` INT NOT NULL,
  PRIMARY KEY (`Movie_Title`, `Movie_ReleaseYear`, `Movie_Company_Name`, `Competition_Name`),
  INDEX `fk_Movie_has_Competition_Competition1_idx` (`Competition_Name` ASC) VISIBLE,
  INDEX `fk_Movie_has_Competition_Movie1_idx` (`Movie_Title` ASC, `Movie_ReleaseYear` ASC, `Movie_Company_Name` ASC) VISIBLE,
  CONSTRAINT `fk_Movie_has_Competition_Movie1`
    FOREIGN KEY (`Movie_Title` , `Movie_ReleaseYear` , `Movie_Company_Name`)
    REFERENCES `mydb`.``` (`Title` , `ReleaseYear` , `Company_Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Movie_has_Competition_Competition1`
    FOREIGN KEY (`Competition_Name`)
    REFERENCES `mydb`.`Competition` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Local Movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Local Movie` (
  `Title` VARCHAR(45) NOT NULL,
  `ReleaseYear` YEAR(4) NOT NULL,
  `Company_Name` VARCHAR(45) NOT NULL,
  `Script_Title` VARCHAR(45) NOT NULL,
  `Script_Genre_Name` VARCHAR(45) NOT NULL,
  `Director_Name` VARCHAR(45) NOT NULL,
  `Director_Game_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Title`, `Director_Name`, `Director_Game_Name`),
  INDEX `fk_Local Movie_Company1_idx` (`Company_Name` ASC) VISIBLE,
  INDEX `fk_Local Movie_Script1_idx` (`Script_Title` ASC, `Script_Genre_Name` ASC) VISIBLE,
  INDEX `fk_Local Movie_Director1_idx` (`Director_Name` ASC, `Director_Game_Name` ASC) VISIBLE,
  CONSTRAINT `fk_Local Movie_Company1`
    FOREIGN KEY (`Company_Name`)
    REFERENCES `mydb`.`Company` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Local Movie_Script1`
    FOREIGN KEY (`Script_Title` , `Script_Genre_Name`)
    REFERENCES `mydb`.`Script` (`Title` , `Genre_Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Local Movie_Director1`
    FOREIGN KEY (`Director_Name` , `Director_Game_Name`)
    REFERENCES `mydb`.`Director` (`Name` , `Game_Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`International Movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`International Movie` (
  `Title` VARCHAR(45) NOT NULL,
  `ReleaseYear` DATE NOT NULL,
  `Company_Name` VARCHAR(45) NOT NULL,
  `Script_Title` VARCHAR(45) NOT NULL,
  `Script_Genre_Name` VARCHAR(45) NOT NULL,
  `Director_Name` VARCHAR(45) NOT NULL,
  `Director_Game_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Title`, `Director_Name`, `Director_Game_Name`),
  INDEX `fk_International Movie_Company1_idx` (`Company_Name` ASC) VISIBLE,
  INDEX `fk_International Movie_Script1_idx` (`Script_Title` ASC, `Script_Genre_Name` ASC) VISIBLE,
  INDEX `fk_International Movie_Director1_idx` (`Director_Name` ASC, `Director_Game_Name` ASC) VISIBLE,
  CONSTRAINT `fk_International Movie_Company1`
    FOREIGN KEY (`Company_Name`)
    REFERENCES `mydb`.`Company` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_International Movie_Script1`
    FOREIGN KEY (`Script_Title` , `Script_Genre_Name`)
    REFERENCES `mydb`.`Script` (`Title` , `Genre_Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_International Movie_Director1`
    FOREIGN KEY (`Director_Name` , `Director_Game_Name`)
    REFERENCES `mydb`.`Director` (`Name` , `Game_Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Actor_plays_in_Local Movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Actor_plays_in_Local Movie` (
  `Actor_Name` VARCHAR(45) NOT NULL,
  `Actor_Photo` BLOB NOT NULL,
  `Local Movie_Title` VARCHAR(45) NOT NULL,
  `Local Movie_Director_Name` VARCHAR(45) NOT NULL,
  `Local Movie_Director_Game_Name` VARCHAR(45) NOT NULL,
  `StartDate` DATE NOT NULL,
  `EndDate` DATE NOT NULL,
  `YearlyPay` INT NOT NULL,
  PRIMARY KEY (`Actor_Name`, `Actor_Photo`, `Local Movie_Title`, `Local Movie_Director_Name`, `Local Movie_Director_Game_Name`),
  INDEX `fk_Actor_has_Local Movie_Local Movie2_idx` (`Local Movie_Title` ASC, `Local Movie_Director_Name` ASC, `Local Movie_Director_Game_Name` ASC) VISIBLE,
  INDEX `fk_Actor_has_Local Movie_Actor2_idx` (`Actor_Name` ASC, `Actor_Photo` ASC) VISIBLE,
  CONSTRAINT `fk_Actor_has_Local Movie_Actor2`
    FOREIGN KEY (`Actor_Name` , `Actor_Photo`)
    REFERENCES `mydb`.`Actor` (`Name` , `Photo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Actor_has_Local Movie_Local Movie2`
    FOREIGN KEY (`Local Movie_Title` , `Local Movie_Director_Name` , `Local Movie_Director_Game_Name`)
    REFERENCES `mydb`.`Local Movie` (`Title` , `Director_Name` , `Director_Game_Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Local Movie_takes_part_in_Competition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Local Movie_takes_part_in_Competition` (
  `Local Movie_Title` VARCHAR(45) NOT NULL,
  `Local Movie_Director_Name` VARCHAR(45) NOT NULL,
  `Local Movie_Director_Game_Name` VARCHAR(45) NOT NULL,
  `Competition_Name` VARCHAR(45) NOT NULL,
  `Nominations` INT NOT NULL,
  `AwardsWon` INT NOT NULL,
  PRIMARY KEY (`Local Movie_Title`, `Local Movie_Director_Name`, `Local Movie_Director_Game_Name`, `Competition_Name`),
  INDEX `fk_Local Movie_has_Competition_Competition1_idx` (`Competition_Name` ASC) VISIBLE,
  INDEX `fk_Local Movie_has_Competition_Local Movie1_idx` (`Local Movie_Title` ASC, `Local Movie_Director_Name` ASC, `Local Movie_Director_Game_Name` ASC) VISIBLE,
  CONSTRAINT `fk_Local Movie_has_Competition_Local Movie1`
    FOREIGN KEY (`Local Movie_Title` , `Local Movie_Director_Name` , `Local Movie_Director_Game_Name`)
    REFERENCES `mydb`.`Local Movie` (`Title` , `Director_Name` , `Director_Game_Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Local Movie_has_Competition_Competition1`
    FOREIGN KEY (`Competition_Name`)
    REFERENCES `mydb`.`Competition` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`International Movie_has_Sponsor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`International Movie_has_Sponsor` (
  `International Movie_Title` VARCHAR(45) NOT NULL,
  `Sponsor_Name` VARCHAR(45) NOT NULL,
  `MoneyOffered` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`International Movie_Title`, `Sponsor_Name`),
  INDEX `fk_International Movie_has_Sponsor_Sponsor1_idx` (`Sponsor_Name` ASC) VISIBLE,
  INDEX `fk_International Movie_has_Sponsor_International Movie1_idx` (`International Movie_Title` ASC) VISIBLE,
  CONSTRAINT `fk_International Movie_has_Sponsor_International Movie1`
    FOREIGN KEY (`International Movie_Title`)
    REFERENCES `mydb`.`International Movie` (`Title`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_International Movie_has_Sponsor_Sponsor1`
    FOREIGN KEY (`Sponsor_Name`)
    REFERENCES `mydb`.`Sponsor` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Actor_plays_in_International Movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Actor_plays_in_International Movie` (
  `Actor_Name` VARCHAR(45) NOT NULL,
  `Actor_Photo` BLOB NOT NULL,
  `International Movie_Title` VARCHAR(45) NOT NULL,
  `International Movie_Director_Name` VARCHAR(45) NOT NULL,
  `International Movie_Director_Game_Name` VARCHAR(45) NOT NULL,
  `StartDate` DATE NOT NULL,
  `EndDate` DATE NOT NULL,
  `YearlyPay` INT NOT NULL,
  PRIMARY KEY (`Actor_Name`, `Actor_Photo`, `International Movie_Title`, `International Movie_Director_Name`, `International Movie_Director_Game_Name`),
  INDEX `fk_Actor_has_International Movie_International Movie2_idx` (`International Movie_Title` ASC, `International Movie_Director_Name` ASC, `International Movie_Director_Game_Name` ASC) VISIBLE,
  INDEX `fk_Actor_has_International Movie_Actor2_idx` (`Actor_Name` ASC, `Actor_Photo` ASC) VISIBLE,
  CONSTRAINT `fk_Actor_has_International Movie_Actor2`
    FOREIGN KEY (`Actor_Name` , `Actor_Photo`)
    REFERENCES `mydb`.`Actor` (`Name` , `Photo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Actor_has_International Movie_International Movie2`
    FOREIGN KEY (`International Movie_Title` , `International Movie_Director_Name` , `International Movie_Director_Game_Name`)
    REFERENCES `mydb`.`International Movie` (`Title` , `Director_Name` , `Director_Game_Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Actor_plays_in_Local Movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Actor_plays_in_Local Movie` (
  `Actor_Name` VARCHAR(45) NOT NULL,
  `Actor_Photo` BLOB NOT NULL,
  `Local Movie_Title` VARCHAR(45) NOT NULL,
  `Local Movie_Director_Name` VARCHAR(45) NOT NULL,
  `Local Movie_Director_Game_Name` VARCHAR(45) NOT NULL,
  `StartDate` DATE NOT NULL,
  `EndDate` DATE NOT NULL,
  `YearlyPay` INT NOT NULL,
  PRIMARY KEY (`Actor_Name`, `Actor_Photo`, `Local Movie_Title`, `Local Movie_Director_Name`, `Local Movie_Director_Game_Name`),
  INDEX `fk_Actor_has_Local Movie_Local Movie2_idx` (`Local Movie_Title` ASC, `Local Movie_Director_Name` ASC, `Local Movie_Director_Game_Name` ASC) VISIBLE,
  INDEX `fk_Actor_has_Local Movie_Actor2_idx` (`Actor_Name` ASC, `Actor_Photo` ASC) VISIBLE,
  CONSTRAINT `fk_Actor_has_Local Movie_Actor2`
    FOREIGN KEY (`Actor_Name` , `Actor_Photo`)
    REFERENCES `mydb`.`Actor` (`Name` , `Photo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Actor_has_Local Movie_Local Movie2`
    FOREIGN KEY (`Local Movie_Title` , `Local Movie_Director_Name` , `Local Movie_Director_Game_Name`)
    REFERENCES `mydb`.`Local Movie` (`Title` , `Director_Name` , `Director_Game_Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Local Movie_has_Sponsor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Local Movie_has_Sponsor` (
  `Local Movie_Title` VARCHAR(45) NOT NULL,
  `Local Movie_Director_Name` VARCHAR(45) NOT NULL,
  `Local Movie_Director_Game_Name` VARCHAR(45) NOT NULL,
  `Sponsor_Name` VARCHAR(45) NOT NULL,
  `MoneyOffered` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Local Movie_Title`, `Local Movie_Director_Name`, `Local Movie_Director_Game_Name`, `Sponsor_Name`),
  INDEX `fk_Local Movie_has_Sponsor1_Sponsor1_idx` (`Sponsor_Name` ASC) VISIBLE,
  INDEX `fk_Local Movie_has_Sponsor1_Local Movie1_idx` (`Local Movie_Title` ASC, `Local Movie_Director_Name` ASC, `Local Movie_Director_Game_Name` ASC) VISIBLE,
  CONSTRAINT `fk_Local Movie_has_Sponsor1_Local Movie1`
    FOREIGN KEY (`Local Movie_Title` , `Local Movie_Director_Name` , `Local Movie_Director_Game_Name`)
    REFERENCES `mydb`.`Local Movie` (`Title` , `Director_Name` , `Director_Game_Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Local Movie_has_Sponsor1_Sponsor1`
    FOREIGN KEY (`Sponsor_Name`)
    REFERENCES `mydb`.`Sponsor` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`International Movie_takes_part_in_Competition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`International Movie_takes_part_in_Competition` (
  `International Movie_Title` VARCHAR(45) NOT NULL,
  `International Movie_Director_Name` VARCHAR(45) NOT NULL,
  `International Movie_Director_Game_Name` VARCHAR(45) NOT NULL,
  `Competition_Name` VARCHAR(45) NOT NULL,
  `Nominations` INT NOT NULL,
  `AwardsWon` INT NOT NULL,
  PRIMARY KEY (`International Movie_Title`, `International Movie_Director_Name`, `International Movie_Director_Game_Name`, `Competition_Name`),
  INDEX `fk_International Movie_has_Competition_Competition1_idx` (`Competition_Name` ASC) VISIBLE,
  INDEX `fk_International Movie_has_Competition_International Movie1_idx` (`International Movie_Title` ASC, `International Movie_Director_Name` ASC, `International Movie_Director_Game_Name` ASC) VISIBLE,
  CONSTRAINT `fk_International Movie_has_Competition_International Movie1`
    FOREIGN KEY (`International Movie_Title` , `International Movie_Director_Name` , `International Movie_Director_Game_Name`)
    REFERENCES `mydb`.`International Movie` (`Title` , `Director_Name` , `Director_Game_Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_International Movie_has_Competition_Competition1`
    FOREIGN KEY (`Competition_Name`)
    REFERENCES `mydb`.`Competition` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`International Movie_is_set_in_Country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`International Movie_is_set_in_Country` (
  `International Movie_Title` VARCHAR(45) NOT NULL,
  `International Movie_Director_Name` VARCHAR(45) NOT NULL,
  `International Movie_Director_Game_Name` VARCHAR(45) NOT NULL,
  `Country_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`International Movie_Title`, `International Movie_Director_Name`, `International Movie_Director_Game_Name`, `Country_Name`),
  INDEX `fk_International Movie_has_Country_Country1_idx` (`Country_Name` ASC) VISIBLE,
  INDEX `fk_International Movie_has_Country_International Movie1_idx` (`International Movie_Title` ASC, `International Movie_Director_Name` ASC, `International Movie_Director_Game_Name` ASC) VISIBLE,
  CONSTRAINT `fk_International Movie_has_Country_International Movie1`
    FOREIGN KEY (`International Movie_Title` , `International Movie_Director_Name` , `International Movie_Director_Game_Name`)
    REFERENCES `mydb`.`International Movie` (`Title` , `Director_Name` , `Director_Game_Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_International Movie_has_Country_Country1`
    FOREIGN KEY (`Country_Name`)
    REFERENCES `mydb`.`Country` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Actor_plays_in_International Movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Actor_plays_in_International Movie` (
  `Actor_Name` VARCHAR(45) NOT NULL,
  `Actor_Photo` BLOB NOT NULL,
  `International Movie_Title` VARCHAR(45) NOT NULL,
  `International Movie_Director_Name` VARCHAR(45) NOT NULL,
  `International Movie_Director_Game_Name` VARCHAR(45) NOT NULL,
  `StartDate` DATE NOT NULL,
  `EndDate` DATE NOT NULL,
  `YearlyPay` INT NOT NULL,
  PRIMARY KEY (`Actor_Name`, `Actor_Photo`, `International Movie_Title`, `International Movie_Director_Name`, `International Movie_Director_Game_Name`),
  INDEX `fk_Actor_has_International Movie_International Movie2_idx` (`International Movie_Title` ASC, `International Movie_Director_Name` ASC, `International Movie_Director_Game_Name` ASC) VISIBLE,
  INDEX `fk_Actor_has_International Movie_Actor2_idx` (`Actor_Name` ASC, `Actor_Photo` ASC) VISIBLE,
  CONSTRAINT `fk_Actor_has_International Movie_Actor2`
    FOREIGN KEY (`Actor_Name` , `Actor_Photo`)
    REFERENCES `mydb`.`Actor` (`Name` , `Photo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Actor_has_International Movie_International Movie2`
    FOREIGN KEY (`International Movie_Title` , `International Movie_Director_Name` , `International Movie_Director_Game_Name`)
    REFERENCES `mydb`.`International Movie` (`Title` , `Director_Name` , `Director_Game_Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SocialMedia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SocialMedia` (
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Director_is_friends_with_Director`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Director_is_friends_with_Director` (
  `Director_Name` VARCHAR(45) NOT NULL,
  `Director_Game_Name` VARCHAR(45) NOT NULL,
  `Director_Name1` VARCHAR(45) NOT NULL,
  `Director_Game_Name1` VARCHAR(45) NOT NULL,
  `SocialMedia_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Director_Name`, `Director_Game_Name`, `Director_Name1`, `Director_Game_Name1`, `SocialMedia_Name`),
  INDEX `fk_Director_has_Director_Director4_idx` (`Director_Name1` ASC, `Director_Game_Name1` ASC) VISIBLE,
  INDEX `fk_Director_has_Director_Director3_idx` (`Director_Name` ASC, `Director_Game_Name` ASC) VISIBLE,
  INDEX `fk_Director_is_friends_with_Director_SocialMedia1_idx` (`SocialMedia_Name` ASC) VISIBLE,
  CONSTRAINT `fk_Director_has_Director_Director3`
    FOREIGN KEY (`Director_Name` , `Director_Game_Name`)
    REFERENCES `mydb`.`Director` (`Name` , `Game_Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Director_has_Director_Director4`
    FOREIGN KEY (`Director_Name1` , `Director_Game_Name1`)
    REFERENCES `mydb`.`Director` (`Name` , `Game_Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Director_is_friends_with_Director_SocialMedia1`
    FOREIGN KEY (`SocialMedia_Name`)
    REFERENCES `mydb`.`SocialMedia` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`International Movie_has_Sponsor1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`International Movie_has_Sponsor1` (
  `International Movie_Title` VARCHAR(45) NOT NULL,
  `International Movie_Director_Name` VARCHAR(45) NOT NULL,
  `International Movie_Director_Game_Name` VARCHAR(45) NOT NULL,
  `Sponsor_Name` VARCHAR(45) NOT NULL,
  `MoneyOffered` INT NOT NULL,
  PRIMARY KEY (`International Movie_Title`, `International Movie_Director_Name`, `International Movie_Director_Game_Name`, `Sponsor_Name`),
  INDEX `fk_International Movie_has_Sponsor1_Sponsor1_idx` (`Sponsor_Name` ASC) VISIBLE,
  INDEX `fk_International Movie_has_Sponsor1_International Movie1_idx` (`International Movie_Title` ASC, `International Movie_Director_Name` ASC, `International Movie_Director_Game_Name` ASC) VISIBLE,
  CONSTRAINT `fk_International Movie_has_Sponsor1_International Movie1`
    FOREIGN KEY (`International Movie_Title` , `International Movie_Director_Name` , `International Movie_Director_Game_Name`)
    REFERENCES `mydb`.`International Movie` (`Title` , `Director_Name` , `Director_Game_Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_International Movie_has_Sponsor1_Sponsor1`
    FOREIGN KEY (`Sponsor_Name`)
    REFERENCES `mydb`.`Sponsor` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Local Movie_is_uploaded_in_SocialMedia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Local Movie_is_uploaded_in_SocialMedia` (
  `Local Movie_Title` VARCHAR(45) NOT NULL,
  `Local Movie_Director_Name` VARCHAR(45) NOT NULL,
  `Local Movie_Director_Game_Name` VARCHAR(45) NOT NULL,
  `SocialMedia_Name` VARCHAR(45) NOT NULL,
  `Likes` INT NOT NULL,
  PRIMARY KEY (`Local Movie_Title`, `Local Movie_Director_Name`, `Local Movie_Director_Game_Name`, `SocialMedia_Name`),
  INDEX `fk_Local Movie_has_SocialMedia_SocialMedia1_idx` (`SocialMedia_Name` ASC) VISIBLE,
  INDEX `fk_Local Movie_has_SocialMedia_Local Movie1_idx` (`Local Movie_Title` ASC, `Local Movie_Director_Name` ASC, `Local Movie_Director_Game_Name` ASC) VISIBLE,
  CONSTRAINT `fk_Local Movie_has_SocialMedia_Local Movie1`
    FOREIGN KEY (`Local Movie_Title` , `Local Movie_Director_Name` , `Local Movie_Director_Game_Name`)
    REFERENCES `mydb`.`Local Movie` (`Title` , `Director_Name` , `Director_Game_Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Local Movie_has_SocialMedia_SocialMedia1`
    FOREIGN KEY (`SocialMedia_Name`)
    REFERENCES `mydb`.`SocialMedia` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`International Movie_is_uploaded_in_SocialMedia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`International Movie_is_uploaded_in_SocialMedia` (
  `International Movie_Title` VARCHAR(45) NOT NULL,
  `International Movie_Director_Name` VARCHAR(45) NOT NULL,
  `International Movie_Director_Game_Name` VARCHAR(45) NOT NULL,
  `SocialMedia_Name` VARCHAR(45) NOT NULL,
  `Likes` INT NOT NULL,
  PRIMARY KEY (`International Movie_Title`, `International Movie_Director_Name`, `International Movie_Director_Game_Name`, `SocialMedia_Name`),
  INDEX `fk_International Movie_has_SocialMedia_SocialMedia1_idx` (`SocialMedia_Name` ASC) VISIBLE,
  INDEX `fk_International Movie_has_SocialMedia_International Movie1_idx` (`International Movie_Title` ASC, `International Movie_Director_Name` ASC, `International Movie_Director_Game_Name` ASC) VISIBLE,
  CONSTRAINT `fk_International Movie_has_SocialMedia_International Movie1`
    FOREIGN KEY (`International Movie_Title` , `International Movie_Director_Name` , `International Movie_Director_Game_Name`)
    REFERENCES `mydb`.`International Movie` (`Title` , `Director_Name` , `Director_Game_Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_International Movie_has_SocialMedia_SocialMedia1`
    FOREIGN KEY (`SocialMedia_Name`)
    REFERENCES `mydb`.`SocialMedia` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Competition_has_page_in_SocialMedia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Competition_has_page_in_SocialMedia` (
  `Competition_Name` VARCHAR(45) NOT NULL,
  `SocialMedia_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Competition_Name`, `SocialMedia_Name`),
  INDEX `fk_Competition_has_SocialMedia_SocialMedia1_idx` (`SocialMedia_Name` ASC) VISIBLE,
  INDEX `fk_Competition_has_SocialMedia_Competition1_idx` (`Competition_Name` ASC) VISIBLE,
  CONSTRAINT `fk_Competition_has_SocialMedia_Competition1`
    FOREIGN KEY (`Competition_Name`)
    REFERENCES `mydb`.`Competition` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Competition_has_SocialMedia_SocialMedia1`
    FOREIGN KEY (`SocialMedia_Name`)
    REFERENCES `mydb`.`SocialMedia` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pantheon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pantheon` (
  `Director_Name` VARCHAR(45) NOT NULL,
  `Director_Game_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Director_Name`, `Director_Game_Name`),
  INDEX `fk_Pantheon_Director1_idx` (`Director_Name` ASC, `Director_Game_Name` ASC) VISIBLE,
  CONSTRAINT `fk_Pantheon_Director1`
    FOREIGN KEY (`Director_Name` , `Director_Game_Name`)
    REFERENCES `mydb`.`Director` (`Name` , `Game_Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Actor_is_from_Country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Actor_is_from_Country` (
  `Actor_Name` VARCHAR(45) NOT NULL,
  `Actor_Photo` BLOB NOT NULL,
  `Country_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Actor_Name`, `Actor_Photo`, `Country_Name`),
  INDEX `fk_Actor_has_Country_Country2_idx` (`Country_Name` ASC) VISIBLE,
  INDEX `fk_Actor_has_Country_Actor2_idx` (`Actor_Name` ASC, `Actor_Photo` ASC) VISIBLE,
  CONSTRAINT `fk_Actor_has_Country_Actor2`
    FOREIGN KEY (`Actor_Name` , `Actor_Photo`)
    REFERENCES `mydb`.`Actor` (`Name` , `Photo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Actor_has_Country_Country2`
    FOREIGN KEY (`Country_Name`)
    REFERENCES `mydb`.`Country` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
